version: '2' 
services:
  totp-auth:
    image: alpine
    container_name: totp-auth

    volumes:
      - ./data:/opt
    environment:
      TZ: Europe/Berlin
      SECRET: 3EYUCWBS2LN7AJGV
    expose: 
      - 80
    networks:
      - proxy_default      

    command: >
              sh -c -x '
              apk add tzdata python3
              && date
              && pip3 install --upgrade pip pyotp
              && cd /opt/
              && echo $$SECRET > .totp_secret
              && python3 /opt/main.py'
              
              
  totp-example:
    image: nginx
    container_name: totp-example
    volumes:
      - ./data/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
